version: "3.7"

services:

  vue:
    container_name: vue
    restart: always
    build: 
      context: .
      dockerfile: ./docker/vue/Dockerfile
    command: npm run serve
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www