version: "3.7"

services:

  vue:
    image: savioli/britecore-frontend:latest
    container_name: vue
    restart: always
    build: 
      context: .
      dockerfile: ./deploy/vue/Dockerfile
    env_file:
      - ./deploy/vue/vue.prod.env
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
    networks:
      - savioli

networks:
  savioli:
    driver: bridge