version: "3.7"

services:

  vue:
    image: vue/prod
    container_name: vue
    restart: always
    build: 
      context: .
      dockerfile: ./deploy/vue/Dockerfile
    env_file:
      - ./deploy/vue/vue.prod.env
    ports:
      - "3000:3000"