version: "3.7"

services:

  vue:
    image: savioli/britecore-frontend:latest
    container_name: vue
    restart: always
    build: 
      context: .
      dockerfile: ./deploy/vue/Dockerfile
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    networks:
      - savioli-network

networks:
  savioli-network:
    driver: bridge